
### All User OK
GET http://localhost:3001/users/all
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjcyMjk3MTB9.SIVypiNWviSlcttsGRkevzuJDMo-OZveLf-AQaCYAWA



#################################################
#                 REGISTER                      #
#################################################

### Register add user
POST http://localhost:3001/users/register
Content-Type: application/json

{
  "username": "new5@test.com",
  "password": "test",
  "isVerified" : true
}

### Register add user
POST http://localhost:3001/users/register
Content-Type: application/json

{
  "username": "test2@test.com",
  "password": "test"
}

### Register add user
POST http://localhost:3001/users/register
Content-Type: application/json

{
  "username": "test3@test.com",
  "password": "test"
}



#################################################


### Login WIP
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "test"
}

### Login WIP
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "username": "new5@test.com",
  "password": "test"
}


### ADMIN

### All Transaction 
GET http://localhost:3001/admin/transactions


### EDIT USER
PUT http://localhost:3001/admin/update/1
Authorization: token AKJZEDHEJFBKEZFNBJQHDBFJL
Content-Type: application/json

{
  "username": "change@test.com",
  "password": ""
}

### DELETE USER
DELETE  http://localhost:3001/users/delete/38
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjcyMjk3MTB9.SIVypiNWviSlcttsGRkevzuJDMo-OZveLf-AQaCYAWA
