
### All User OK
GET http://localhost:3001/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjcyMjk3MTB9.SIVypiNWviSlcttsGRkevzuJDMo-OZveLf-AQaCYAWA


### Update User 
PUT http://localhost:3001/users/42
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjczMTA4NjV9._UOSMaztyLeDIRo4vYOMACalhe8J7ARovpd4GZ3j6jE
Content-Type: application/json

{
 "username" : "modif@test.fr",
 "password" : "test",
 "lastName" : "khrfda",
 "firstName" : "khdfra",
 "phone" : "0616209779",
 "societyName" : "AAAA",
 "contact" : "pipouzzz21@gmail.com",
 "kabis" : "9854",
 "confirmationUrl" : "test.fr",
 "cancelUrl" : "test.com",
 "currency" : "eur"
}


#################################################
#                 REGISTER                      #
#################################################

### Register add user
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "yanis2@test.com",
  "password": "password"
}

### Register add user
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "test2@test.com",
  "password": "test"
}

### Register add user
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "test3@test.com",
  "password": "test"
}



#################################################


### Login WIP
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "yanis2@test.com",
  "password": "test"
}


### ADMIN

### All Transaction 
GET http://localhost:3001/admin/transactions


### EDIT USER
PUT http://localhost:3001/admin/update/1
Authorization: token AKJZEDHEJFBKEZFNBJQHDBFJL
Content-Type: application/json

{
  "username": "change@test.com",
  "password": ""
}

### DELETE USER
DELETE  http://localhost:3001/users/delete/38
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjcyMjk3MTB9.SIVypiNWviSlcttsGRkevzuJDMo-OZveLf-AQaCYAWA
